In [11]:
a=[5,6,7]

b=a.pop()


a.insert(2, 'yassine')

In [12]:
a

[5, 6, 'yassine']

# Chaos function

In [23]:
def main():
    print('This program illustrates a chaotic function.')
    print ('This is to illustrates that we can write some text here.')
    x= float(input('Enter a number between 0 and 1: '))
    y=float(input('Enter a second number between 0 and 1: '))
    for i in range(10):
        x=3.9*x*(1-x)
        y=3.9*x*(1-y)
        print(' ')
        print('############')
        print(f'{x:.2f}')
        print(f'{y:.2f}')
                   
main()

This program illustrates a chaotic function.
This is to illustrates that we can write some text here.
Enter a number between 0 and 1: 0.2
Enter a second number between 0 and 1: 0.6

############
0.62
0.97

############
0.92
0.09

############
0.30
1.07

############
0.82
-0.23

############
0.57
2.71

############
0.96
-6.37

############
0.16
4.49

############
0.51
-7.01

############
0.97
30.42

############
0.10
-11.24

In [38]:
n=list(range(1,11))
print(n)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
m=range(10)
type(m)

range

In [42]:
m

range(0, 10)

In [53]:
m='Hello yassine'
d=enumerate(m)
f=list(d)
f

[(0, 'H'),
 (1, 'e'),
 (2, 'l'),
 (3, 'l'),
 (4, 'o'),
 (5, ' '),
 (6, 'y'),
 (7, 'a'),
 (8, 's'),
 (9, 's'),
 (10, 'i'),
 (11, 'n'),
 (12, 'e')]

In [55]:
s='this is good'
p=enumerate(s)
p

In [65]:
y,=p.(0)

SyntaxError: invalid syntax (<ipython-input-65-a2e243036681>, line 1)

In [70]:
a=range(10)
b=a
for i in a: #loop1
    print('###### LOOP 1 ####')
    print('  ')
    print('Bravo mehdi')
    print('###### LOOP 1 ####')
    print('  ')
    for f in b: #loop2
        print('###### LOOP 2 ####')
        print('  ')
        print("you're the one mehdi")
        print('##### LOOP2 ####')
        print('  ')

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 1 ####

Bravo mehdi
###### LOOP 1 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

###### LOOP 2 ####

you're the one mehdi
##### LOOP2 ####

In [ ]:
import random
game=['Rock', 'Paper', 'Scissors']
player_score=0
computer_score=0
player_choice=input('a vous de jouer: pierre, papier, ciseaux: \t').upper()
computer_choice=random.choice(game).upper()

while player_score<3 or computer_score<3:
    if player_choice == computer_choice:
        print('DRAW')
        print(' ')
        print(' ')
        print(' ')
    elif player_choice == 'ROCK' and computer_choice == 'PAPER':
        print('YOU LOSE')
        computer_score +=1
        print(' ')
        print(' ')
        print(' ')
    elif player_choice == 'ROCK' and computer_choice == 'SCISSORS':
        print('YOU WIN')
        player_score+=1
        print(' ')
        print(' ')
        print(' ')
    elif player_choice == 'PAPER' and computer_choice == 'SCISSORS':
        print('YOU LOSE')
        computer_score+=1
        print(' ')
        print(' ')
        print(' ')
    elif player_choice == 'PAPER' and computer_choice == 'ROCK':
        print('YOU WIN')
        player_score+=1
        print(' ')
        print(' ')
        print(' ')
    elif player_choice == 'SCISSORS' and computer_choice == 'PAPER':
        print('YOU WIN')
        player_score+=1
        print(' ')
        print(' ')
        print(' ')
    elif player_choice == 'SCISSORS' and computer_choice == 'ROCK':
        print('YOU LOSE')
        computer_score+=1
        print(' ')
        print(' ')
    else:
        print('you entered an invalid entry')
        print(' ')
        print(' ')
        print(' ')

In [1]:
import random

In [14]:
data = [
    {
        'name': 'Instagram',
        'follower_count': 346,
        'description': 'Social media platform',
        'country': 'United States'
    },
    {
        'name': 'Cristiano Ronaldo',
        'follower_count': 215,
        'description': 'Footballer',
        'country': 'Portugal'
    },
    {
        'name': 'Ariana Grande',
        'follower_count': 183,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Dwayne Johnson',
        'follower_count': 181,
        'description': 'Actor and professional wrestler',
        'country': 'United States'
    },
    {
        'name': 'Selena Gomez',
        'follower_count': 174,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Kylie Jenner',
        'follower_count': 172,
        'description': 'Reality TV personality and businesswoman and Self-Made Billionaire',
        'country': 'United States'
    },
    {
        'name': 'Kim Kardashian',
        'follower_count': 167,
        'description': 'Reality TV personality and businesswoman',
        'country': 'United States'
    },
    {
        'name': 'Lionel Messi',
        'follower_count': 149,
        'description': 'Footballer',
        'country': 'Argentina'
    },
    {
        'name': 'Beyoncé',
        'follower_count': 145,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Neymar',
        'follower_count': 138,
        'description': 'Footballer',
        'country': 'Brasil'
    },
    {
        'name': 'National Geographic',
        'follower_count': 135,
        'description': 'Magazine',
        'country': 'United States'
    },
    {
        'name': 'Justin Bieber',
        'follower_count': 133,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Taylor Swift',
        'follower_count': 131,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Kendall Jenner',
        'follower_count': 127,
        'description': 'Reality TV personality and Model',
        'country': 'United States'
    },
    {
        'name': 'Jennifer Lopez',
        'follower_count': 119,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Nicki Minaj',
        'follower_count': 113,
        'description': 'Musician',
        'country': 'Trinidad and Tobago'
    },
    {
        'name': 'Nike',
        'follower_count': 109,
        'description': 'Sportswear multinational',
        'country': 'United States'
    },
    {
        'name': 'Khloé Kardashian',
        'follower_count': 108,
        'description': 'Reality TV personality and businesswoman',
        'country': 'United States'
    },
    {
        'name': 'Miley Cyrus',
        'follower_count': 107,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Katy Perry',
        'follower_count': 94,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Kourtney Kardashian',
        'follower_count': 90,
        'description': 'Reality TV personality',
        'country': 'United States'
    },
    {
        'name': 'Kevin Hart',
        'follower_count': 89,
        'description': 'Comedian and actor',
        'country': 'United States'
    },
    {
        'name': 'Ellen DeGeneres',
        'follower_count': 87,
        'description': 'Comedian',
        'country': 'United States'
    },
    {
        'name': 'Real Madrid CF',
        'follower_count': 86,
        'description': 'Football club',
        'country': 'Spain'
    },
    {
        'name': 'FC Barcelona',
        'follower_count': 85,
        'description': 'Football club',
        'country': 'Spain'
    },
    {
        'name': 'Rihanna',
        'follower_count': 81,
        'description': 'Musician and businesswoman',
        'country': 'Barbados'
    },
    {
        'name': 'Demi Lovato',
        'follower_count': 80,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': "Victoria's Secret",
        'follower_count': 69,
        'description': 'Lingerie brand',
        'country': 'United States'
    },
    {
        'name': 'Zendaya',
        'follower_count': 68,
        'description': 'Actress and musician',
        'country': 'United States'
    },
    {
        'name': 'Shakira',
        'follower_count': 66,
        'description': 'Musician',
        'country': 'Colombia'
    },
    {
        'name': 'Drake',
        'follower_count': 65,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Chris Brown',
        'follower_count': 64,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'LeBron James',
        'follower_count': 63,
        'description': 'Basketball player',
        'country': 'United States'
    },
    {
        'name': 'Vin Diesel',
        'follower_count': 62,
        'description': 'Actor',
        'country': 'United States'
    },
    {
        'name': 'Cardi B',
        'follower_count': 67,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'David Beckham',
        'follower_count': 82,
        'description': 'Footballer',
        'country': 'United Kingdom'
    },
    {
        'name': 'Billie Eilish',
        'follower_count': 61,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Justin Timberlake',
        'follower_count': 59,
        'description': 'Musician and actor',
        'country': 'United States'
    },
    {
        'name': 'UEFA Champions League',
        'follower_count': 58,
        'description': 'Club football competition',
        'country': 'Europe'
    },
    {
        'name': 'NASA',
        'follower_count': 56,
        'description': 'Space agency',
        'country': 'United States'
    },
    {
        'name': 'Emma Watson',
        'follower_count': 56,
        'description': 'Actress',
        'country': 'United Kingdom'
    },
    {
        'name': 'Shawn Mendes',
        'follower_count': 57,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Virat Kohli',
        'follower_count': 55,
        'description': 'Cricketer',
        'country': 'India'
    },
    {
        'name': 'Gigi Hadid',
        'follower_count': 54,
        'description': 'Model',
        'country': 'United States'
    },
    {
        'name': 'Priyanka Chopra Jonas',
        'follower_count': 53,
        'description': 'Actress and musician',
        'country': 'India'
    },
    {
        'name': '9GAG',
        'follower_count': 52,
        'description': 'Social media platform',
        'country': 'China'
    },
    {
        'name': 'Ronaldinho',
        'follower_count': 51,
        'description': 'Footballer',
        'country': 'Brasil'
    },
    {
        'name': 'Maluma',
        'follower_count': 50,
        'description': 'Musician',
        'country': 'Colombia'
    },
    {
        'name': 'Camila Cabello',
        'follower_count': 49,
        'description': 'Musician',
        'country': 'Cuba'
    },
    {
        'name': 'NBA',
        'follower_count': 47,
        'description': 'Club Basketball Competition',
        'country': 'United States'
    }
]

In [15]:
logo = """
    __  ___       __             
   / / / (_)___ _/ /_  ___  _____
  / /_/ / / __ `/ __ \/ _ \/ ___/
 / __  / / /_/ / / / /  __/ /    
/_/ ///_/\__, /_/ /_/\___/_/     
   / /  /____/_      _____  _____
  / /   / __ \ | /| / / _ \/ ___/
 / /___/ /_/ / |/ |/ /  __/ /    
/_____/\____/|__/|__/\___/_/     
"""

vs = """
 _    __    
| |  / /____
| | / / ___/
| |/ (__  ) 
|___/____(_)
"""

In [15]:
import random

In [51]:
choice=random.choices(data)

print(f"{choice[0]['name']}, {choice[0]['follower_count']}, { choice[0]['country']}")

Gigi Hadid, 54, United States

In [52]:
type(choice)

list

In [53]:
choice[0]['name']

'Gigi Hadid'

In [57]:
choice[0].items()

dict_items([('name', 'Gigi Hadid'), ('follower_count', 54), ('description', 'Model'), ('country', 'United States')])

In [58]:
type(choice[0])

dict

In [2]:
yassine ='yassine'
yass= enumerate(yassine)

In [4]:
print(list(yass))

[(0, 'y'), (1, 'a'), (2, 's'), (3, 's'), (4, 'i'), (5, 'n'), (6, 'e')]

In [16]:
import random
def item_extractor(data):
    return random.choice(data)

In [18]:
item_extractor(data)['follower_count']

80